export * from "./Paragraph/ParagraphComponent"
export * from "./Title/TitleComponent"
export * from "./Image/ImageComponent"
export * from "./Main/MainComponent"
export * from "./SubTitle/SubtitleComponent"
