export * from "./Register/Register";
export * from "./Home/Home";
export * from "./Login/Login"
export * from "./Dashboard/Dashboard"
export * from "./CodeConfirmation/CodeConfirmation"
export * from "./NotFound/NotFound"
export * from "./Profile/Profile"
export * from "./ChangePassword/ChangePassword"
export * from "./DeleteUser/DeleteUser"
export * from "./ProfileUpdate/ProfileUpdate"
export * from "./SingleAlbumPage/SingleAlbumPage"
export * from "./CreateAlbum/CreateAlbum"
export * from "./FavAlbumsTab/FavAlbumsTab"
